services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"        # opcional, solo si quieres acceder desde el host
    volumes:
      - mongo-data:/data/db  # persistencia de Mongo

  predict:
    build: ./predict         # usa tu Dockerfile de este proyecto
    image: predict:1.0       # nombre de imagen
    container_name: predict
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env.docker          # variables de entorno
    ports:
      - "3002:3002"          # host:contenedor

  acquire:
    build: ./acquire
    image: acquire:1.0
    container_name: acquire
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env.docker
    ports:
      - "3001:3001"


volumes:
  mongo-data: